(list
 '((#:name . "ipdb-packages")
   (#:load-path-inputs . ("guix"))
   (#:package-path-inputs . ("packages"))
   (#:proc-input . "conf")
   (#:proc-file . "ci/jobs.scm")
   (#:proc . cuirass-jobs)
   ;; (#:proc-args (subset . "foo"))
   (#:inputs . (((#:name . "guix")
                 (#:url . "git://git.savannah.gnu.org/guix.git")
                 (#:load-path . ".")
                 (#:branch . "master")
                 (#:no-compile? . #t))
                ((#:name . "conf")
                 (#:url . "git@github.com:ipdb/ipdb-guix.git")
                 (#:load-path . ".")
                 (#:branch . "ci")
                 (#:no-compile? . #t))
                ((#:name . "packages")
                 (#:url . "git@github.com:ipdb/ipdb-guix.git")
                 (#:load-path . ".")
                 (#:branch . "master")
                 (#:no-compile? . #t))))))
